version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      GitHub Actions Minor or Patch:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directory: /
    groups:
      Cargo dev-dependencies:
        dependency-type: development
    schedule:
      interval: monthly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
