version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-or-patch:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directory: /
    groups:
      dev-dependencies:
        dependency-type: development
    schedule:
      interval: monthly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
