version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /
    groups:
      dev-dependencies:
        dependency-type: development
    schedule:
      interval: monthly
