[package]
name = "rpsl-parser"
version = "0.1.0"
edition = "2021"
authors = ["Marvin Vogt <m@rvinvogt.com>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/srv6d/rpsl-parser"
repository = "https://github.com/srv6d/rpsl-parser"
readme = "README.md"

[dependencies]
nom = "7.1.3"
