---
name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number
    || github.sha }}
  cancel-in-progress: true

env:
  COLUMNS: 120
  HYPERFINE_VERSION: "1.17.0"

jobs:
  cargo-bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: run benchmark
        run: cargo bench -- --output-format bencher | tee output.txt
      - name: store the result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: cargo
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.event_name != 'pull_request' }}
          alert-threshold: 150%
          comment-on-alert: true
          fail-on-alert: true
