---
name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
      - uses: taiki-e/install-action@65835784ace7c5a78745b6dbeb9bf85346430497
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@513a19673a831f139e8717bf45ead67e47f00044
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
