---
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number
    || github.sha }}
  cancel-in-progress: true

env:
  COLUMNS: 120

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Format
        run: cargo fmt --all --check
  cargo-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
  property-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          command: build
          args: --release
      - name: install dependencies
        run: pip3 install pytest hypothesis .
      - name: Test
        run: pytest tests/property_based
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip3 install codespell
      - uses: codespell-project/codespell-problem-matcher@v1
      - name: check for typos
        run: codespell src/ tests/ docs/ README.md
