---
name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ["1.74", "stable"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8
        with:
          toolchain: ${{ matrix.rust_version }}
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
      - uses: taiki-e/install-action@684122deb17127bf60d1d99224e12e8fc0012210
        with:
          tool: cargo-llvm-cov
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

      - name: Test
        run: just test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
        with:
          name: Rust ${{ matrix.rust_version }}
          files: lcov.info
          use_oidc: true
          fail_ci_if_error: true
